version: 0.2
phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/PollLifx
      - dotnet restore
      - dotnet lambda package
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - aws cloudformation package --template-file cloudformation.yml --s3-bucket $LAMBDA_BUCKET --output-template-file out.yml
artifacts:
  files:
    - out.yml
    - cloudformation-config.json