AWSTemplateFormatVersion: 2010-09-09
Description: Scehduled lambda to poll lifx api and store the current state of lightbulbs
Parameters:
  CodeS3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the lambda function code
  CodeS3Key:
    Type: String
    Description: S3 key for the lambda function code
  CodeS3ObjectVersion:
    Type: String
    Description: S3 object version for the lambda function code
  LifxApiUrl:
    Type: String
    Description: Lifx Api Url
    Default: https://api.lifx.com
  LifxToken:
    Type: String
    Description: Lifx Api Token
  LambdaSchedule:
    Type: String
    Description: Cloudwatch Event Rule ScheduleExpression for invoking the lambda function
    Default: rate(5 minutes)
  ReadCapacity:
    Type: Number
    Description: Provisioned read throughput for the DynamoDB Table
    Default: 1
  WriteCapacity:
    Type: Number
    Description: Provisioned write throughput for the DynamoDB Table
    Default: 1
Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: FunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:describetable
                  - dynamodb:putitem
                Resource: !GetAtt Table.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Handler: PollLifx::PollLifx.Function::FunctionHandler
      Role: !GetAtt FunctionRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
        S3ObjectVersion: !Ref CodeS3ObjectVersion
      MemorySize: 256
      Runtime: dotnetcore2.0
      Timeout: 15
      Environment:
        Variables:
          LifxApiUrl: !Ref LifxApiUrl
          LifxToken: !Ref LifxToken
          DynamoDbTableName: !Ref Table
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule
      ScheduleExpression: !Ref LambdaSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt Function.Arn
          Id: TargetFunction
  ScheduledRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Function
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacity
        WriteCapacityUnits: !Ref WriteCapacity
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  TableStreamArn:
    Value: !GetAtt Table.StreamArn
    Export:
      Name: !Sub "${AWS::StackName}-TableStreamArn"