AWSTemplateFormatVersion: 2010-09-09
Description: Scehduled lambda to poll lifx api and store the current state of lightbulbs
Parameters:
  LifxApiUrl:
    Type: String
    Description: Lifx Api Url
    Default: https://api.lifx.com
  LifxToken:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Lifx Api Token
    Default: LifxToken
  LambdaSchedule:
    Type: String
    Description: Cloudwatch Event Rule ScheduleExpression for invoking the lambda function
    Default: rate(5 minutes)
  ReadCapacity:
    Type: Number
    Description: Provisioned read throughput for the DynamoDB Table
    Default: 1
  WriteCapacity:
    Type: Number
    Description: Provisioned write throughput for the DynamoDB Table
    Default: 1
Resources:
  SyncStateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SyncStatePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:describetable
                  - dynamodb:putitem
                Resource: !GetAtt State.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  SyncState:
    Type: AWS::Lambda::Function
    Properties:
      Handler: PollLifx.SyncState::PollLifx.SyncState.Function::FunctionHandler
      Role: !GetAtt SyncStateRole.Arn
      Code: ./PollLifx.SyncState/bin/Release/netcoreapp2.0/PollLifx.SyncState.zip
      MemorySize: 256
      Runtime: dotnetcore2.0
      Timeout: 15
      Environment:
        Variables:
          LifxApiUrl: !Ref LifxApiUrl
          LifxToken: !Ref LifxToken
          DynamoDbTableName: !Ref State
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule
      ScheduleExpression: !Ref LambdaSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt SyncState.Arn
          Id: TargetFunction
  ScheduledRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SyncState
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn
  State:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacity
        WriteCapacityUnits: !Ref WriteCapacity
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  StateStreamArn:
    Value: !GetAtt State.StreamArn
    Export:
      Name: !Sub "${AWS::StackName}-StateStreamArn"